language: python
python:
  - "3.7"

install:
  - pip install .
  - pip install nose-cov

script:
  - nosetests --with-coverage --cover-package=quart_compress

after_success:
  - pip install coveralls
  - coveralls
