language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - pip install nose-cov

script:
  - nosetests --with-coverage

after_success:
  - pip install coveralls
  - coveralls
